sudo: required
dist: trusty

language:
  - python
python:
  - "2.7"
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/virtualenv
    - parser

install:
  # Install all dependencies as per our README
  - pip install -r python-package-requirement.txt
  - test -e parser/corenlp.sh || ./install-parser.sh

  # Use runipy to run Jupyter/IPython notebooks from command-line
  - pip install runipy

script:
  # Make sure the notebooks run end-to-end
  - runipy GeneTaggerExample_Extraction.ipynb
  - runipy GeneTaggerExample_Learning.ipynb

  # TODO check outputs, upload results, etc.
  # for more ideas, see: https://github.com/rossant/ipycache/issues/7
