sudo: false  # to use container-based infra, see: http://docs.travis-ci.com/user/migrating-from-legacy/
language:
  - python
python:
  - "2.7"

cache:
  directories:
    - parser
    - /home/travis/virtualenv

addons:
  apt:
    packages:
      # Some Python packages aren't possible to install w/ pip
    - python-numpy
    - python-scipy
      # for CoreNLP
    - oracle-java8-installer

# Need the following lines to use system-wide Python packages from our virtualenv
# See: http://stackoverflow.com/a/18986891
virtualenv:
  system_site_packages: true

install:
  - pip install -r python-package-requirement.txt --use-mirrors
  - ./install-parser.sh

  # Use runipy to run Jupyter/IPython notebooks from command-line
  # For more ideas, see: https://github.com/rossant/ipycache/issues/7
  - pip install runipy

script:
  - runipy GeneTaggerExample_Extraction.ipynb
  - runipy GeneTaggerExample_Learning.ipynb
